name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Show files
        run: |
          pwd
          ls
          find . -name "gradlew"

      - name: Make gradlew executable
        run: chmod +x ./AI-Translator-2026-06-12-b86ee/gradlew

      - name: Build Debug APK
        run: cd AI-Translator-2026-06-12-b86ee && ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AI_Translator_APK
          path: AI-Translator-2026-06-12-b86ee/app/build/outputs/apk/debug/*.apk
